# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 508ba12e3d3ba5c2ba2d6be8c0bb7b31d8a87ccb12e194e74612ccd459d6de695f2fcd7fa21ae018676ea2aa596c7d547849ad817697409409531fc9f467b153

test:
  secret_key_base: e3c1fdb73667c1ce850e611ba9ea1cc10c236e79e31602de2af272b8b8edef48b1a0249ca49c374a55852921e813f9697c1b7891e226bd71cbe0620abeb83e5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
